version: 0.2

phases:
  install:
    commands:
      - echo "Installation des dépendances"

  build:
    commands:
      - echo "Démarrage du build"
      - mkdir -p output
      - zip -r output/build.zip ./

  post_build:
    commands:
      - echo "Upload vers S3"
      - aws s3 cp output/build.zip s3://automationbucketalph/
